version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "9e:21:30:79:40:47:09:75:61:53:d7:83:ff:d9:8c:0c"
      - run:
          name: Deploy
          command: |
            # 6- Give the ingress rule some time to propogate
            sleep 5
            # 7- SSH to the server to deploy
            # TODO Change to your username
            EC2_USERNAME=ubuntu
            # TODO Change to your server's URL or public IP
            EC2_PUBLIC_DNS=ec2-100-24-206-98.compute-1.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS 'sudo apt update && sudo apt install apache2 -y'
            # TODO Perform steps to deploy
            # .
            # .
deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: AWS EC2 deploy
          command: |
            sleep 5
            EC2_USERNAME=ubuntu
            EC2_PUBLIC_DNS=ec2-100-24-206-98.compute-1.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS 'echo Start deploy && cd pruebagit/hello-circleci/ && sudo git pull && sudo cp index.html /var/www/html/ && sudo service apache2 restart && echo Deploy end'
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
