 version: 2

 workflows: 
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master 
 jobs:
   build:
     docker: 
       - image: ubuntu 
         auth:
           username: mydockerhub-user
           password: $DOCKERHUB_PASSWORD 
 ... 
 deploy:
     docker: # Specify executor for running deploy job
       - image: ubuntu # Specify docker image to use
         auth:
           username: mydockerhub-user
           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
     steps:
       - run: # Install the AWS CLI if it is not already included in the docker image
           name: Install awscli 
           command: sudo pip install awscli
       - run: # Deploy to S3 using the sync command
           name: Deploy to S3
           command: aws s3 sync <path/to/bucket> <s3://location/in/S3-to-deploy-to>
